'use client';

import { useState, useEffect } from 'react';
import { useProjectStore } from '@/hooks/useProject';
import { api } from '@/lib/api';
import { ApprovalGate } from '../ApprovalGate';
import { Rocket, Loader2, ExternalLink, CheckCircle2 } from 'lucide-react';

function buildPreviewFiles(
  summary: string,
  features: { name: string; description: string; priority: string }[],
  techStack: { category: string; choice: string }[],
  repoUrl: string
): { path: string; content: string }[] {
  const featuresList = features
    .map((f) => `<li><strong>${f.name}</strong> <span class="badge ${f.priority}">${f.priority}</span><br><span class="desc">${f.description}</span></li>`)
    .join('\n          ');
  const stackList = techStack
    .map((t) => `<li><strong>${t.category}:</strong> ${t.choice}</li>`)
    .join('\n          ');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project Preview</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0a; color: #e5e5e5; min-height: 100vh; padding: 2rem; }
    .container { max-width: 720px; margin: 0 auto; }
    h1 { font-size: 1.75rem; margin-bottom: 0.5rem; color: #fff; }
    .summary { color: #a3a3a3; margin-bottom: 2rem; line-height: 1.6; }
    h2 { font-size: 1.1rem; color: #818cf8; margin-bottom: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }
    ul { list-style: none; margin-bottom: 2rem; }
    li { padding: 0.75rem; border: 1px solid #262626; border-radius: 8px; margin-bottom: 0.5rem; background: #111; }
    .desc { color: #a3a3a3; font-size: 0.875rem; }
    .badge { font-size: 0.7rem; padding: 2px 8px; border-radius: 9999px; text-transform: uppercase; font-weight: 600; }
    .badge.must { background: #7f1d1d; color: #fca5a5; }
    .badge.should { background: #78350f; color: #fcd34d; }
    .badge.could { background: #1e3a5f; color: #93c5fd; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #262626; font-size: 0.8rem; color: #525252; }
    a { color: #818cf8; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .tag { display: inline-block; background: #1e1e2e; padding: 2px 10px; border-radius: 4px; font-size: 0.8rem; margin: 2px; color: #a3a3a3; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Project Preview</h1>
    <p class="summary">${summary}</p>

    <h2>MVP Features</h2>
    <ul>
      ${featuresList}
    </ul>

    <h2>Tech Stack</h2>
    <ul>
      ${stackList}
    </ul>

    <div class="footer">
      <p>Generated by <strong>DevForge</strong> &middot; <a href="${repoUrl}" target="_blank">View on GitHub</a></p>
      <p style="margin-top: 0.5rem;">This is a project preview page. Clone the repo and run the scaffold to start developing.</p>
    </div>
  </div>
</body>
</html>`;

  return [{ path: 'index.html', content: html }];
}

export function DeploySetup() {
  const { project, setProject, addLog } = useProjectStore();
  const [generating, setGenerating] = useState(false);
  const [deploying, setDeploying] = useState(false);
  const [netlifyToml, setNetlifyToml] = useState(project?.deploy?.netlifyToml ?? '');
  const [envVars, setEnvVars] = useState(project?.deploy?.envVars ?? []);
  const [deployed, setDeployed] = useState(!!project?.deploy?.siteUrl);

  useEffect(() => {
    if (!project?.deploy && project?.plan) {
      generateConfig();
    }
  }, []);

  async function generateConfig() {
    if (!project?.plan) return;
    setGenerating(true);
    addLog({ level: 'info', step: 'deploy', message: 'Generating deploy configuration...' });

    try {
      const techStack = project.plan.techStack
        .map((t) => `${t.category}: ${t.choice}`)
        .join(', ');
      const config = await api.generateDeployConfig(techStack, 'web-app', true, project.settings);

      setNetlifyToml(config.netlifyToml);
      setEnvVars(config.envVars);
      addLog({ level: 'success', step: 'deploy', message: 'Deploy configuration generated' });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Config generation failed';
      addLog({ level: 'error', step: 'deploy', message });
    } finally {
      setGenerating(false);
    }
  }

  async function handleApprove() {
    if (!project?.repoResult) return;
    setDeploying(true);

    try {
      // Step 1: Commit netlify.toml to repo
      addLog({ level: 'info', step: 'deploy', message: 'Committing netlify.toml...' });
      await api.commitFiles(
        project.repoResult.fullName,
        [{ path: 'netlify.toml', content: netlifyToml }],
        'chore: add netlify configuration'
      );

      // Step 2: Create Netlify site and deploy a static preview page
      addLog({ level: 'info', step: 'deploy', message: 'Creating Netlify site and deploying preview...' });
      const siteName = project.repoResult.fullName.split('/')[1];

      // Build a static HTML preview from the plan (Netlify file deploy serves files as-is)
      const previewFiles = buildPreviewFiles(
        project.plan?.summary ?? 'Project',
        project.plan?.mvpFeatures ?? [],
        project.plan?.techStack ?? [],
        project.repoResult.url
      );

      const result = await api.linkNetlify(
        project.repoResult.fullName,
        siteName,
        project.scaffold?.buildCommand ?? 'npm run build',
        project.scaffold?.publishDir ?? 'dist',
        previewFiles
      );

      const deploy = {
        netlifyToml,
        envVars,
        siteId: result.siteId,
        siteUrl: result.siteUrl,
      };

      const updated = {
        ...project,
        deploy,
        updatedAt: new Date().toISOString(),
        steps: {
          ...project.steps,
          deploy: { ...project.steps.deploy, status: 'completed' as const, approvedAt: new Date().toISOString(), completedAt: new Date().toISOString() },
        },
      };

      setProject(updated);
      setDeployed(true);
      addLog({ level: 'success', step: 'deploy', message: `Site deployed: ${result.siteUrl}` });
      api.saveProject(updated).catch(() => {});
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Deployment failed';
      addLog({ level: 'error', step: 'deploy', message });
    } finally {
      setDeploying(false);
    }
  }

  function handleBack() {
    if (!project) return;
    const updated = {
      ...project,
      currentStep: 'docs' as const,
      updatedAt: new Date().toISOString(),
      steps: {
        ...project.steps,
        docs: { ...project.steps.docs, status: 'active' as const },
        deploy: { ...project.steps.deploy, status: 'locked' as const },
      },
    };
    setProject(updated);
  }

  if (deployed && project?.deploy?.siteUrl) {
    return (
      <div className="mx-auto max-w-2xl text-center py-16">
        <CheckCircle2 className="h-16 w-16 text-success mx-auto mb-6" />
        <h2 className="text-2xl font-bold mb-2">Project Deployed!</h2>
        <p className="text-muted mb-6">Your project is live and ready to go.</p>

        <div className="space-y-3">
          {project.repoResult && (
            <a
              href={project.repoResult.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 text-accent hover:text-accent-hover text-sm"
            >
              GitHub: {project.repoResult.fullName}
              <ExternalLink className="h-3.5 w-3.5" />
            </a>
          )}
          <a
            href={project.deploy.siteUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 text-accent hover:text-accent-hover text-sm"
          >
            Netlify: {project.deploy.siteUrl}
            <ExternalLink className="h-3.5 w-3.5" />
          </a>
        </div>
      </div>
    );
  }

  if (generating) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-accent mb-4" />
        <p className="text-muted text-sm">Generating deploy configuration...</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl">
      <div className="flex items-center gap-3 mb-6">
        <Rocket className="h-6 w-6 text-accent" />
        <h2 className="text-xl font-semibold">Deployment Setup</h2>
      </div>

      {/* netlify.toml editor */}
      <div className="mb-6">
        <label className="block text-sm font-medium text-muted mb-1.5">netlify.toml</label>
        <textarea
          value={netlifyToml}
          onChange={(e) => setNetlifyToml(e.target.value)}
          rows={12}
          className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground font-mono focus:border-accent focus:outline-none resize-none"
        />
      </div>

      {/* Environment Variables */}
      {envVars.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-medium text-muted mb-3">Environment Variables Checklist</h3>
          <div className="rounded-lg border border-border bg-surface overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left text-muted">
                  <th className="px-4 py-2 font-medium">Variable</th>
                  <th className="px-4 py-2 font-medium">Description</th>
                  <th className="px-4 py-2 font-medium text-center">Required</th>
                </tr>
              </thead>
              <tbody>
                {envVars.map((v, i) => (
                  <tr key={i} className="border-b border-border/50">
                    <td className="px-4 py-2 font-mono text-xs text-accent">{v.key}</td>
                    <td className="px-4 py-2 text-muted">{v.description}</td>
                    <td className="px-4 py-2 text-center">
                      {v.required ? (
                        <span className="text-error text-xs font-medium">Required</span>
                      ) : (
                        <span className="text-muted text-xs">Optional</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <ApprovalGate
        warning="This will commit netlify.toml to your repo and create a Netlify site linked to your GitHub repository."
        approveLabel="Deploy to Netlify"
        onApprove={handleApprove}
        onBack={handleBack}
        loading={deploying}
      />
    </div>
  );
}
